// Copyright (c) 2024, Cogent Core. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package book is the book-specific version of Cogent Author for
// rendering markdown source into various book documents,
// including .pdf via latex, .html, .docx and epub.
//
// These files should be located in the current directory where the command
// is run.  Author generates the output files based on Book.Name there,
// with all of the temporary files used in the generation process in the
// 'author' directory.
package book

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"

	"cogentcore.org/cogent/author"
	coshell "cogentcore.org/core/shell"
	"cogentcore.org/core/shell/cosh"
)

// Code generated by "cosh transpile"; DO NOT EDIT.

var shell = coshell.NewShell()

// Book generates a book based on a set of markdown files, with the
// following required file names (with [] indicating optional files):
//
//   - metadata.yaml: pandoc metadata with various important options
//   - frontmatter.md: with copyright, dedication, foreward, preface, prologue sections.
//   - chapter-*.md chapters, using 01 etc numbering to put in order.
//   - endmatter.md: includes epilogue, acknowledgements, author
//   - [appendix-*.md] appendicies, using a, b, c, etc labeling.
//   - [glossary.md] optional glossary that generates links in text.
//   - references are auto-generated from citations in text.
func Book(c *author.Config) error { //types:add
	name := c.Output
	if name == "" {
		name = "book"
	}
	book := NewBookData(name)
	book.savePandocInputs()
	mdfn := book.Markdown()
	var errs []error
	for _, fmt := range c.Formats {
		switch fmt {
		case author.PDF:
			err := book.PDF(mdfn)
			if err != nil {
				errs = append(errs, err)
			}
		case author.HTML:
			err := book.HTML(mdfn)
			if err != nil {
				errs = append(errs, err)
			}
		}
	}
	return errors.Join(errs...)
}

// BookData has all of the info about the book.
type BookData struct {
	// Name is the overall name of the book.
	// Output files will be Name.pdf etc.
	Name string

	// names of the chapters, in sorted order.
	Chapters []string

	// names of the appendicies.
	Appendicies []string
}

func NewBookData(name string) *BookData {
	return &BookData{Name: name}
}

func (bk *BookData) pandocMarkdownOpts() string {
	pdi := bk.pandocInputs()
	opts := "markdown+smart+line_blocks+escaped_line_breaks+fenced_code_blocks+fenced_code_attributes+backtick_code_blocks+yaml_metadata_block"
	opts += "-F " + filepath.Join(pdi, "pandoc-filter.py") + " --lua-filter " + filepath.Join(pdi, "glossary-filter.lua")
	return opts
}

// PDF generates PDF file from given markdown filename
func (bk *BookData) PDF(mdfn string) error {
	mdopts := bk.pandocMarkdownOpts()
	shell.Run("pandoc", "-f", mdopts)
	return nil
}

// HTML generates HTML file from given markdown filename
func (bk *BookData) HTML(mdfn string) error {
	mdopts := bk.pandocMarkdownOpts()
	trg := bk.Name + ".html"
	shell.Run("pandoc", "-f", mdopts, "-t", "html", "--standalone", "--embed-resources", "--number-sections", "--css=../author/html.css", "-H", "../author/head_include.html", "-o", trg, mdfn)
	return nil
}

// Markdown generates the combined markdown file that everything else works on.
func (bk *BookData) Markdown() string {
	os.MkdirAll("author", 0750)
	fn := "author/book.md"
	bk.GetFiles()
	bk.Metadata(fn)
	shell.Run("cat", "frontmatter.md", ">>", fn)
	for ci, ch := range bk.Chapters {
		chdiv := fmt.Sprintf("<div class=\"book_section\" id=\"chapter%02d\">", ci)
		shell.Run("echo", chdiv, ">>", fn)
		shell.Run("cat", ch, ">>", fn)
		shell.Run("echo", "</div>", ">>", fn)
	}
	shell.Run("cat", "endmatter.md", ">>", fn)
	// todo: appendix
	if cosh.FileExists("glossary.md") {
		shell.Run("echo", "<div class=\"book_section\" =id=\"glossary\">", ">>", fn)
		shell.Run("cat", "glossary.md", ">>", fn)
		shell.Run("echo", "</div>", ">>", fn)
	}
	shell.Run("echo", "<div class=\"book_section\" =id=\"references\">", ">>", fn)
	shell.Run("echo", "# References", ">>", fn)
	shell.Run("echo", "</div>", ">>", fn)
	return fn
}

func (bk *BookData) GetFiles() {
	bk.Chapters = cosh.SplitLines(shell.Output("ls", "chapter-*.md"))
	sort.Strings(bk.Chapters)
	if cosh.FileExists("appendix-a.md") {
		bk.Appendicies = cosh.SplitLines(shell.Output("ls", "appendix-*.md"))
		sort.Strings(bk.Appendicies)
	}
}

// Metadata outputs the medadata to book.md file
func (bk *BookData) Metadata(fn string) {
	shell.Run("echo", "---", ">", fn)
	shell.Run("cat", "metadata.yaml", ">>", fn)
	shell.RunErrOK("cat", "references.yaml", ">>", fn)
}

func (bk *BookData) pandocInputs() string {
	return filepath.Join("author", "pandoc-inputs")
}

// savePandocInputs saves the embedded pandoc inputs in author dir
func (bk *BookData) savePandocInputs() {
	pdi := bk.pandocInputs()
	os.MkdirAll(pdi, 0750)
	fns, _ := fs.Glob(PandocInputs, "*")
	for _, fn := range fns {
		fc, _ := fs.ReadFile(PandocInputs, fn)
		_, fb := path.Split(fn)
		tf := filepath.Join(pdi, fb)
		cosh.WriteFile(tf, string(fc))
	}
}
