// Code generated by 'yaegi extract cogentcore.org/core/tensor/stats/simat'. DO NOT EDIT.

package imports

import (
	"cogentcore.org/core/tensor/stats/simat"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/core/tensor/stats/simat/simat"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BlankRepeat": reflect.ValueOf(simat.BlankRepeat),
		"Tensor":      reflect.ValueOf(simat.Tensor),
		"TensorStd":   reflect.ValueOf(simat.TensorStd),
		"Tensors":     reflect.ValueOf(simat.Tensors),
		"TensorsStd":  reflect.ValueOf(simat.TensorsStd),

		// type definitions
		"SimMat": reflect.ValueOf((*simat.SimMat)(nil)),
	}
}
