// Code generated by 'yaegi extract cogentcore.org/core/tensor/stats/convolve'. DO NOT EDIT.

package imports

import (
	"cogentcore.org/core/tensor/stats/convolve"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/core/tensor/stats/convolve/convolve"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GaussianKernel32": reflect.ValueOf(convolve.GaussianKernel32),
		"GaussianKernel64": reflect.ValueOf(convolve.GaussianKernel64),
		"Slice32":          reflect.ValueOf(convolve.Slice32),
		"Slice64":          reflect.ValueOf(convolve.Slice64),
		"SmoothTable":      reflect.ValueOf(convolve.SmoothTable),
	}
}
