// Code generated by 'yaegi extract cogentcore.org/core/tensor/bitslice'. DO NOT EDIT.

package imports

import (
	"cogentcore.org/core/tensor/bitslice"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/core/tensor/bitslice/bitslice"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BitIndex": reflect.ValueOf(bitslice.BitIndex),
		"Make":     reflect.ValueOf(bitslice.Make),

		// type definitions
		"Slice": reflect.ValueOf((*bitslice.Slice)(nil)),
	}
}
