// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gide

const (
	Version     = "v1.0.24"
	GitCommit   = "6a4ccf9"          // the commit JUST BEFORE the release
	VersionDate = "2021-10-27 11:31" // UTC
)
