// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gide

const (
	Version     = "v1.0.8"
	GitCommit   = "971d81e" // the commit JUST BEFORE the release
	VersionDate = "2020-09-04 21:56" // UTC
)

