// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gide

const (
	Version     = "v1.1.5"
	GitCommit   = "a9fe305"          // the commit JUST BEFORE the release
	VersionDate = "2023-01-06 01:42" // UTC
)
