// Code generated by "stringer -type=ArgVarTypes"; DO NOT EDIT.

package gide

import (
	"fmt"
	"strconv"
)

const _ArgVarTypes_name = "ArgVarFileArgVarDirArgVarExtArgVarPosArgVarTextArgVarPromptArgVarTypesN"

var _ArgVarTypes_index = [...]uint8{0, 10, 19, 28, 37, 47, 59, 71}

func (i ArgVarTypes) String() string {
	if i < 0 || i >= ArgVarTypes(len(_ArgVarTypes_index)-1) {
		return "ArgVarTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArgVarTypes_name[_ArgVarTypes_index[i]:_ArgVarTypes_index[i+1]]
}

func (i *ArgVarTypes) FromString(s string) error {
	for j := 0; j < len(_ArgVarTypes_index)-1; j++ {
		if s == _ArgVarTypes_name[_ArgVarTypes_index[j]:_ArgVarTypes_index[j+1]] {
			*i = ArgVarTypes(j)
			return nil
		}
	}
	return fmt.Errorf("String %v is not a valid option for type ArgVarTypes", s)
}
