name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Provide a clear and concise description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    id: example-code
    attributes:
      label: Example code
      description: If applicable, provide code that can be used reproduce the bug. This will be automatically formatted into code, so no need for backticks.
      render: go
  - type: textarea
    id: output
    attributes:
      label: Relevant output
      description: If applicable, copy and paste any relevant program output / panic messages / stack traces. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
        - Web
    validations:
      required: true

