name: Feature Request
description: Request a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: describe-the-feature
    attributes:
      label: Describe the feature
      description: Provide a clear and concise description of the proposed feature
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Relevant code
      description: If applicable, provide any relevant code that shows how the new feature would work. This will be automatically formatted into code, so no need for backticks.
      render: go
