#!/bin/bash

if [ -z "$GOPATH" ]
then
	export GOPATH="$HOME/go"
fi

# this should get all your env settings:
source $HOME/.bash_profile

# in general don't want to be using modules for development work:
export GO111MODULE=off
export PATH="$GOPATH/bin:$PATH"

"$GOPATH/bin/gide" "$@" > "$HOME/Library/gide/gide.log" 2>&1

