// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package grid

const (
	Version     = "v0.5.0"
	GitCommit   = "ac36bc2" // the commit JUST BEFORE the release
	VersionDate = "2021-03-03 12:01" // UTC
)

