// Code generated by "core generate"; DO NOT EDIT.

package databrowser

import (
	"cogentcore.org/core/icons"
	"cogentcore.org/core/math32"
	"cogentcore.org/core/styles/units"
	"cogentcore.org/core/tree"
	"cogentcore.org/core/types"
	"cogentcore.org/core/views"
)

// BrowserType is the [types.Type] for [Browser]
var BrowserType = types.AddType(&types.Type{Name: "cogentcore.org/cogent/numbers/databrowser.Browser", IDName: "browser", Doc: "Browser is a data browser, for browsing data typically organized into\nseparate directories, with .cosh Scripts as toolbar actions to perform\nregular tasks on the data.\nScripts are ordered alphabetically and any leading #- prefix is automatically\nremoved from the label, so you can use numbers to specify a custom order.", Methods: []types.Method{{Name: "UpdateFiles", Doc: "UpdateFiles Updates the file view with current files in DataRoot,", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}, {Name: "UpdateScripts", Doc: "UpdateScripts updates the Scripts and updates the toolbar.", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}}, Embeds: []types.Field{{Name: "Frame"}}, Fields: []types.Field{{Name: "DataRoot", Doc: "DataRoot is the path to the root of the data to browse"}, {Name: "StartDir", Doc: "StartDir is the starting directory, where the numbers app\nwas originally started."}, {Name: "ScriptsDir", Doc: "ScriptsDir is the directory containing scripts for toolbar actions.\nIt defaults to DataDir/dbscripts"}, {Name: "Scripts", Doc: "Scripts"}, {Name: "ScriptInterp", Doc: "ScriptInterp is the interpreter to use for running Browser scripts"}}, Instance: &Browser{}})

// NewBrowser returns a new [Browser] with the given optional parent:
// Browser is a data browser, for browsing data typically organized into
// separate directories, with .cosh Scripts as toolbar actions to perform
// regular tasks on the data.
// Scripts are ordered alphabetically and any leading #- prefix is automatically
// removed from the label, so you can use numbers to specify a custom order.
func NewBrowser(parent ...tree.Node) *Browser { return tree.New[*Browser](parent...) }

// NodeType returns the [*types.Type] of [Browser]
func (t *Browser) NodeType() *types.Type { return BrowserType }

// New returns a new [*Browser] value
func (t *Browser) New() tree.Node { return &Browser{} }

// SetDataRoot sets the [Browser.DataRoot]:
// DataRoot is the path to the root of the data to browse
func (t *Browser) SetDataRoot(v string) *Browser { t.DataRoot = v; return t }

// SetStartDir sets the [Browser.StartDir]:
// StartDir is the starting directory, where the numbers app
// was originally started.
func (t *Browser) SetStartDir(v string) *Browser { t.StartDir = v; return t }

// SetScriptsDir sets the [Browser.ScriptsDir]:
// ScriptsDir is the directory containing scripts for toolbar actions.
// It defaults to DataDir/dbscripts
func (t *Browser) SetScriptsDir(v string) *Browser { t.ScriptsDir = v; return t }

// SetTooltip sets the [Browser.Tooltip]
func (t *Browser) SetTooltip(v string) *Browser { t.Tooltip = v; return t }

// FileNodeType is the [types.Type] for [FileNode]
var FileNodeType = types.AddType(&types.Type{Name: "cogentcore.org/cogent/numbers/databrowser.FileNode", IDName: "file-node", Doc: "FileNode is Code version of FileNode for FileTree view", Methods: []types.Method{{Name: "EditFiles", Doc: "EditFiles calls EditFile on selected files", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}, {Name: "PlotFiles", Doc: "PlotFiles calls PlotFile on selected files", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}}, Embeds: []types.Field{{Name: "Node"}}, Instance: &FileNode{}})

// NewFileNode returns a new [FileNode] with the given optional parent:
// FileNode is Code version of FileNode for FileTree view
func NewFileNode(parent ...tree.Node) *FileNode { return tree.New[*FileNode](parent...) }

// NodeType returns the [*types.Type] of [FileNode]
func (t *FileNode) NodeType() *types.Type { return FileNodeType }

// New returns a new [*FileNode] value
func (t *FileNode) New() tree.Node { return &FileNode{} }

// SetTooltip sets the [FileNode.Tooltip]
func (t *FileNode) SetTooltip(v string) *FileNode { t.Tooltip = v; return t }

// SetText sets the [FileNode.Text]
func (t *FileNode) SetText(v string) *FileNode { t.Text = v; return t }

// SetIcon sets the [FileNode.Icon]
func (t *FileNode) SetIcon(v icons.Icon) *FileNode { t.Icon = v; return t }

// SetIconOpen sets the [FileNode.IconOpen]
func (t *FileNode) SetIconOpen(v icons.Icon) *FileNode { t.IconOpen = v; return t }

// SetIconClosed sets the [FileNode.IconClosed]
func (t *FileNode) SetIconClosed(v icons.Icon) *FileNode { t.IconClosed = v; return t }

// SetIconLeaf sets the [FileNode.IconLeaf]
func (t *FileNode) SetIconLeaf(v icons.Icon) *FileNode { t.IconLeaf = v; return t }

// SetIndent sets the [FileNode.Indent]
func (t *FileNode) SetIndent(v units.Value) *FileNode { t.Indent = v; return t }

// SetOpenDepth sets the [FileNode.OpenDepth]
func (t *FileNode) SetOpenDepth(v int) *FileNode { t.OpenDepth = v; return t }

// SetViewIndex sets the [FileNode.ViewIndex]
func (t *FileNode) SetViewIndex(v int) *FileNode { t.ViewIndex = v; return t }

// SetWidgetSize sets the [FileNode.WidgetSize]
func (t *FileNode) SetWidgetSize(v math32.Vector2) *FileNode { t.WidgetSize = v; return t }

// SetRootView sets the [FileNode.RootView]
func (t *FileNode) SetRootView(v *views.TreeView) *FileNode { t.RootView = v; return t }

// SetSelectedNodes sets the [FileNode.SelectedNodes]
func (t *FileNode) SetSelectedNodes(v ...views.TreeViewer) *FileNode { t.SelectedNodes = v; return t }
